language: node_js
notifications:
  email: false
node_js:
  - "16"
  - "14"
script:
  - yarn test:prod && yarn build
after_success:
  - yarn travis-deploy-once "yarn report-coverage"
  - if [ "$TRAVIS_BRANCH" = "main" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn travis-deploy-once "yarn semantic-release"; fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
